import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Input } from "@/components/ui/input";
import { RxMagnifyingGlass } from "react-icons/rx";
import { BiSortAlt2 } from "react-icons/bi";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full max-w-md mx-auto bg-background">
          <nav className="px-4 py-2">
            <div className="flex items-center justify-between">
              <h1 className="text-2xl font-bold">Links</h1>
              {/* <div className="flex space-x-4">
                <a href="/" className="text-blue-500 hover:underline">
                  Home
                </a>
                <a href="/posts" className="text-blue-500 hover:underline">
                  Posts
                </a>
              </div> */}
            </div>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
